name: jellomark
description: "JelloMark - Beauty Shop Discovery & Booking Platform"
publish_to: 'none'
version: 1.0.0+18

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.0
  get_it: ^9.2.0
  dio: ^5.9.0
  flutter_secure_storage: ^10.0.0
  collection: ^1.19.1
  equatable: ^2.0.8
  dartz: ^0.10.1
  kakao_flutter_sdk_user: ^1.10.0
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.5
  flutter_naver_map: ^1.3.0
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  cached_network_image: ^3.4.1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.6.1
  build_runner: ^2.10.4
  http_mock_adapter: ^0.6.1
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.4

flutter_native_splash:
  background_image: assets/splash/splash-jellomark02.png
  android_12:
    image: assets/splash/splash-jellomark02.png
    icon_background_color: "#F5E6E0"
    color: "#F5E6E0"
  ios: true
  android: true
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app-icon-jellomark.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  fonts:
    - family: Esamanru
      fonts:
        - asset: assets/fonts/esamanru-Light.ttf
          weight: 300
        - asset: assets/fonts/esamanru-Medium.ttf
          weight: 500
        - asset: assets/fonts/esamanru-Bold.ttf
          weight: 700

  assets:
    - assets/splash/
